* <2014-11-24 Пн.> DONE ошибка https://bugs.launchpad.net/fuel/+bug/1394246
  When vmware vcenter is used, nova-network used one ip range for all vlan networks
** Сначала необходимо воспроизвести окружение:
*** ноды: 1 контроллер A-P-M-F103-S
*** интерфейсы
    A S_{102} M_{101}
    P F_{103}
*** настройки vcenter, nova with vlan-manager, 4 fixed range networks
** Воспроизведение ошибки
   все fixed сети получат один и тот же диапазон ip адресов
   dnsmasq обслуживает разные интерфейсы
   ошибка не воспроизведена ни на убунте, ни на центоси

* ошибка https://bugs.launchpad.net/fuel/+bug/1393497
  Deploy NSX and сompute + multiple roles at one node may cause an error Edit
** окружение
   2 ноды: контроллер и компьюта-синдер-сеф
   интерфейсы:
   A
   P
   M_{101}
   .
   S_{102}
   настройки:
   NSX_USERNAME='admin'
   NSX_PASSWORD= 'admin'
   NSX_TRANSPORT_ZONE='0f12c1f7-5605-46b6-aa3f-4bf50bde47e5'
   L3_SERVICE_UUID='aa153851-bd8e-4852-9772-d98a431849e0'
   NSX_CONTROLLER_ENDPOINT='172.16.1.253'
   URL_TO_NSX_BITS='http://172.18.170.84'
   NSX_CONNECTOR_TYPE='stt'
# 25.11.2014
* работы по ошибке 1394246 завершены
  приступил к 1393497. Развёртываю окружение на fuel-5.1.1-20-2014-11-18_11-07-36.iso
  Образцовое окружение (центось, контроллер и компьюта qemu+nsx) не развернулось по причине:
  Could not set 'present' on ensure: Connection refused - connect(2) at 25:/etc/puppet/modules/l23network/manifests/l2.pp
  подобное же окружение на убунте упало по той же причине:
  Could not set 'present' on ensure: Network is unreachable - connect(2) at 17:/etc/puppet/modules/l23network/manifests/l2.pp
# 26.11.2024
* ошибка 1393497 передана Стёпе
* приступил к https://bugs.launchpad.net/fuel/+bug/1396163
  Fuel 5.1.1 + NSX. Instances do not receive the network configuration
** Проблема: экземляры не получают ip адреса
** Окружение: Fuel 5.1.1, qemu+nsx, HA with 5 CentOS nodes: 3 controller, compute and cinder.
** Воспроизведение: в случае ha не запускается ocf-resource  p_neutron-dhcp-agent и p_neutron-l3-agent.
   Без dhcp-агента не запускается dnsmask, некому выделить ip для виртуалок, ничего не работает.
   Обходной путь --- запустить оные ресурсы руками.
# 27.11.2014 thusday
* Для ошибки 1396163 Андей нашёл обходное решение.
* Описал обходной путь для https://bugs.launchpad.net/fuel/+bug/1365468
* Читал про OpenVSwitch
# 28.11.2014 friday
* гы-гы. Обновление ядра до 3.13 приводит к тому, что у нас полностью не работает NSX.
  это вызвано тем, что перешли на использование внутриядерного openvswitch-datapath
  и в l23network/manifests/l2.pp перестали устанавливать пакеты
  package { 'openvswitch-datapath':
     name => 'openvswitch-datapath-lts-saucy-dkms'
  }
  и
  package { 'openvswitch-datapath':
     name => 'kmod-openvswitch'
  }
  что полностью ломает логику манифестов для nsx.
  для центоси сообщено об ошибке https://bugs.launchpad.net/fuel/+bug/1397290
  решение --- отменить изменение и продолжить ставить модуль kmod-openvswitch: https://review.openstack.org/137776
  для убунты --- ошибка: https://bugs.launchpad.net/fuel/+bug/1397331
  решение --- виртуализовать пакет: https://review.openstack.org/137821
# 01.12.2014 monday
* проверка исправления двух предыдущих ошибок на новой iso Сборка #25 (30.11.2014 22:41:00)
* просмотрел Release Notes 6.0 -- VMware issues. Поставил минус. Постаил плюс.
* начал работы над env-maker
# 02.12.2014 tuesday
* проверил работу vlan-manger на свежей iso в muti-node режиме
* ошибка https://bugs.launchpad.net/fuel/+bug/1386547
  Решение --- увеличить таймауты в ostf тестах.
# 03.13.2014 wednesday
* начал проверку vlan-manager в HA режиме
* продолжил работу над увеличением таймаутов в ostf
  Завершил. коммит вмёржен.
* продолжил работу над env-maker'ом.
#05.12.2014 friday
* составляю список ситуаций, которые проверяют системные тесты
  vcenter_one_node_simple
          Scenario:
            1. Create cluster
            2. Add 1 node with controller role
            3. Deploy the cluster
            4. Validate cluster was set up correctly, there are no dead
            5. Create instance and delete instance.
  vcenter_multiple_cluster
  Scenario:
            1. Create cluster
            2. Add 1 node with controller role
            3. Deploy the cluster
            4. Check that available at least two hypervisor
            5. Create 4 instances
            6. Check connectivity between 2 instances in different hypervisor
  vcenter_vmdk
  Scenario:
            1. Create cluster
            2. Add 2 nodes with controller and cinder roles
            3. Deploy the cluster
            4. Run osft
  vcenter_ha
  Scenario:
            1. Create cluster
            2. Add 3 nodes with controller role
            3. Deploy the cluster
            4. Run osft
  
# 08.12.2014 monday
* продолжил работу над списком тестов

* посетил ретроспективу по 6.0
* приступил к работе над https://review.openstack.org/#/c/140044/
  Проблема в fuel 5.1 ostf тест, проверяющий работу cinder+vmdk падает, а в 6.0 --- работает.
  В системных тестах он помечен как should_fail и когда он падает в 5.1 всё хорошо, а когда работает в 6.0 --- тест не проходит.
  Решение: вставить проверку номера версии и реализовать разное поведение для разных версий.
# 09.12.2014 tuesday
* продолжил работу над 140044
  вмержено
# 10.12.2014 wednesday
* посетил osci митинг
* приступил к https://bugs.launchpad.net/fuel/+bug/1401046
* <2015-01-12 Пн.> Приступил к работе
* <2015-01-13 Вт.>  получил задачу добавить поддержку разных cinder-ролей для vCenter и KVM
** необходимо дооформить [[https://blueprints.launchpad.net/fuel/%2Bspec/cinder-vmdk-role][blueprint]]  и [[https://review.openstack.org/#/c/143419/][спецификацию]]
*** что нужно доделать в спеке
**** TODO 
** реализовать puppet-часть этого. Доделать Стёпин [[https://review.openstack.org/#/c/143954/][патч]]
*** TODO проверить как он работает сейчас
*** TODO разделить конфиги для cinder и cinder-vmdk
*** TODO выкинуть лишнее (данные по vmware из cinder/данные по iscsi из cinder-vmdk)
    из этих конфигов.
*** TODO убедиться, что cinder и cinder-vmdk работают по отдельности
*** TODO убедиться, что cinder и cinder-vmdk работают совместно на одном узле
** добавить изменения в UI
*** TODO добавить новую роль
*** TODO добавить уведомления
*** TODO обеспечить возможность раздельной настройки для cinder и cinder-vmdk нод
** написать тесты
* <2015-01-14 Ср.> продолжаю работать над раздельными cinder нодами
* <2015-01-14 Ср.> приступил к [[https://bugs.launchpad.net/fuel/%2Bbug/1410163][Cluster attrubute use_vcenter value is always true Edit]]
