# 24.11.2014 monday
* DONE ошибка https://bugs.launchpad.net/fuel/+bug/1394246
  When vmware vcenter is used, nova-network used one ip range for all vlan networks
** Сначала необходимо воспроизвести окружение:
*** ноды: 1 контроллер A-P-M-F103-S
*** интерфейсы
    A S_{102} M_{101}
    P F_{103}
*** настройки vcenter, nova with vlan-manager, 4 fixed range networks
** Воспроизведение ошибки
   все fixed сети получат один и тот же диапазон ip адресов
   dnsmasq обслуживает разные интерфейсы
   ошибка не воспроизведена ни на убунте, ни на центоси

* ошибка https://bugs.launchpad.net/fuel/+bug/1393497
  Deploy NSX and сompute + multiple roles at one node may cause an error Edit
** окружение
   2 ноды: контроллер и компьюта-синдер-сеф
   интерфейсы:
   A
   P
   M_{101}
   .
   S_{102}
   настройки:
   NSX_USERNAME='admin'
   NSX_PASSWORD= 'admin'
   NSX_TRANSPORT_ZONE='0f12c1f7-5605-46b6-aa3f-4bf50bde47e5'
   L3_SERVICE_UUID='aa153851-bd8e-4852-9772-d98a431849e0'
   NSX_CONTROLLER_ENDPOINT='172.16.1.253'
   URL_TO_NSX_BITS='http://172.18.170.84'
   NSX_CONNECTOR_TYPE='stt'
# 25.11.2014
* работы по ошибке 1394246 завершены
  приступил к 1393497. Развёртываю окружение на fuel-5.1.1-20-2014-11-18_11-07-36.iso
  Образцовое окружение (центось, контроллер и компьюта qemu+nsx) не развернулось по причине:
  Could not set 'present' on ensure: Connection refused - connect(2) at 25:/etc/puppet/modules/l23network/manifests/l2.pp
  подобное же окружение на убунте упало по той же причине:
  Could not set 'present' on ensure: Network is unreachable - connect(2) at 17:/etc/puppet/modules/l23network/manifests/l2.pp

# 26.11.2024
* ошибка 1393497 передана Стёпе
* приступил к https://bugs.launchpad.net/fuel/+bug/1396163
  Fuel 5.1.1 + NSX. Instances do not receive the network configuration
** Проблема: экземляры не получают ip адреса
** Окружение: Fuel 5.1.1, qemu+nsx, HA with 5 CentOS nodes: 3 controller, compute and cinder.
** Воспроизведение: в случае ha не запускается ocf-resource  p_neutron-dhcp-agent и p_neutron-l3-agent.
   Без dhcp-агента не запускается dnsmask, некому выделить ip для виртуалок, ничего не работает.
   Обходной путь --- запустить оные ресурсы руками.
